print("Hello! Welcome to the wild world of Dunoa\n")
print("In this world, Dragons used to be the scourge that destroyed kingdoms and empires")
print("but are now extinct, with their only remnants being the myths and legends left behind")
print("and their kin, known as the Dragonborn. ")
input("Press enter to continue...\n")

print("Now life flourishes, elves, tritons, dwarves and humans live alongside eachother!")
print("However, that all changed with the human empires of Kestramore, Baldur and Baica")
print("harnessing the power of steam, and taking to the seas to conquer new land and")
print("resources. To the dismay of many elven empires that see these fire breathing machines")
print("as a bad omen and as a sign for the return of the greatest evil, Bakusura")
input("Press enter to continue...\n")

print("In the midst of this war you, dear adventurer, find yourself in the small port city")
print("of Leafice, celebrating the 'great breaking' festival")
input("Press enter to continue...\n")

print("Now tell me. What is your name?")
name = input("My name is: ")

print("\nAh " + name + ". Sounds like the name of a fine adventurer. Now I must know.")
print("It's a bit difficult to tell, but what is your lineage?")
print(" 1. Human")
print(" 2. Elf")
print(" 3. Half-Elf")
print(" 4. Dwarf")
print(" 5. Dragonborn")
print(" 6. Halfling")
race = input("Please enter a number: ")